"use client";

import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

const LanguageContext = createContext({
  lang: "en",
  setLang: () => {},
  toggleLang: () => {},
  t: (key, fallback) => key || fallback || "",
});

export const TRANSLATIONS = {
  en: {
    // Navigation & General
    "Dashboard": "Dashboard",
    "Dictionary": "Dictionary",
    "Leaderboard": "Leaderboard",
    "Suggestions": "Suggestions",
    "Practice": "Practice",
    "Social Hub": "Social Hub",
    "Settings": "Settings",
    "Profile": "Profile",
    "Friends": "Friends",
    "Help & Support": "Help & Support",
    "Logout": "Logout",
    "Sign Out": "Sign Out",
    "Sign In": "Sign In",
    "Login": "Login",
    "Register": "Register",
    "Search": "Search",
    "Loading...": "Loading...",
    "Save": "Save",
    "Cancel": "Cancel",
    "Back": "Back",
    "Help": "Help",
    "Active": "Active",
    "Otakufy Member": "Otakufy Member",
    
    // Dashboard & Objectives
    "Welcome back.": "Welcome back.",
    "\"Continue your path to fluency.\"": "\"Continue your path to fluency.\"",
    "Day Streak": "Day Streak",
    "Total XP": "Total XP",
    "LEVEL": "LEVEL",
    "study_modules": "Study Modules",
    "Kanji": "Kanji",
    "Vocabulary": "Vocabulary",
    "Grammar": "Grammar",
    "Reading": "Reading",
    "Listening": "Listening",
    "Random": "Random",
    "smart_review": "Smart Review",
    "Spaced Repetition": "Spaced Repetition",
    "Power through your due SRS reviews. The algorithm determines exactly what you need to study for optimal long-term retention. If your queue is empty, you'll automatically start a random": "Power through your due SRS reviews. The algorithm determines exactly what you need to study for optimal long-term retention. If your queue is empty, you'll automatically start a random",
    "deck.": "deck.",
    "Start SRS Review": "Start SRS Review",
    "daily_objectives": "Daily Objectives",
    "No quests assigned today.": "No quests assigned today.",
    "Claim": "Claim",
    "Answer 10 Kanji correctly": "Answer 10 Kanji correctly",
    "Learn 10 new Vocabulary words": "Learn 10 new Vocabulary words",
    "Complete 5 Grammar questions": "Complete 5 Grammar questions",
    "Complete 5 Listening exercises": "Complete 5 Listening exercises",
    "Complete 1 quiz session today": "Complete 1 quiz session today",
    "Get 3 correct answers in a row": "Get 3 correct answers in a row",
    "Answer 20 questions correctly in total": "Answer 20 questions correctly in total",
    "Answer 20 Kanji correctly": "Answer 20 Kanji correctly",
    "Learn 20 new Vocabulary words": "Learn 20 new Vocabulary words",
    "Complete 10 Grammar questions": "Complete 10 Grammar questions",
    "Complete 10 Listening exercises": "Complete 10 Listening exercises",
    "Complete 2 quiz sessions today": "Complete 2 quiz sessions today",
    "Get 5 correct answers in a row": "Get 5 correct answers in a row",
    "Answer 30 questions correctly in total": "Answer 30 questions correctly in total",
    "Answer 30 Kanji correctly": "Answer 30 Kanji correctly",
    "Learn 30 new Vocabulary words": "Learn 30 new Vocabulary words",
    "Complete 15 Grammar questions": "Complete 15 Grammar questions",
    "Complete 15 Listening exercises": "Complete 15 Listening exercises",
    "Complete 3 quiz sessions today": "Complete 3 quiz sessions today",
    "Get 10 correct answers in a row": "Get 10 correct answers in a row",
    "Answer 50 Kanji correctly": "Answer 50 Kanji correctly",
    "Learn 50 new Vocabulary words": "Learn 50 new Vocabulary words",
    "Complete 30 Grammar questions": "Complete 30 Grammar questions",
    "Complete 30 Listening exercises": "Complete 30 Listening exercises",
    "Complete 5 quiz sessions today": "Complete 5 quiz sessions today",
    "Get 15 correct answers in a row": "Get 15 correct answers in a row",
    "Answer 60 questions correctly in total": "Answer 60 questions correctly in total",
    "Answer 70 Kanji correctly": "Answer 70 Kanji correctly",
    "Learn 70 new Vocabulary words": "Learn 70 new Vocabulary words",
    "Complete 40 Grammar questions": "Complete 40 Grammar questions",
    "Complete 40 Listening exercises": "Complete 40 Listening exercises",
    "Complete 7 quiz sessions today": "Complete 7 quiz sessions today",
    "Achieve a 100% perfect score in one session": "Achieve a 100% perfect score in one session",
    "Get 25 correct answers in a row": "Get 25 correct answers in a row",
    "Answer 80 questions correctly in total": "Answer 80 questions correctly in total",
    "Answer 90 Kanji correctly": "Answer 90 Kanji correctly",
    "Learn 90 new Vocabulary words": "Learn 90 new Vocabulary words",
    "Complete 50 Grammar questions": "Complete 50 Grammar questions",
    "Complete 50 Listening exercises": "Complete 50 Listening exercises",
    "Complete 10 quiz sessions today": "Complete 10 quiz sessions today",
    "Answer 120 Kanji correctly": "Answer 120 Kanji correctly",
    "Learn 120 new Vocabulary words": "Learn 120 new Vocabulary words",
    "Complete 80 Grammar questions": "Complete 80 Grammar questions",
    "Complete 80 Listening exercises": "Complete 80 Listening exercises",
    "Complete 15 quiz sessions today": "Complete 15 quiz sessions today",
    "Achieve a 100% perfect score in two sessions": "Achieve a 100% perfect score in two sessions",
    "Get 50 correct answers in a row": "Get 50 correct answers in a row",
    "Answer 150 questions correctly in total": "Answer 150 questions correctly in total",
    "Answer 150 Kanji correctly": "Answer 150 Kanji correctly",
    "Learn 150 new Vocabulary words": "Learn 150 new Vocabulary words",
    "Complete 100 Grammar questions": "Complete 100 Grammar questions",
    "Complete 100 Listening exercises": "Complete 100 Listening exercises",
    "Complete 20 quiz sessions today": "Complete 20 quiz sessions today",
    "Achieve a 100% perfect score in three sessions": "Achieve a 100% perfect score in three sessions",
    "Get 80 correct answers in a row": "Get 80 correct answers in a row",
    "Answer 200 questions correctly in total": "Answer 200 questions correctly in total",
    "Answer 250 Kanji correctly": "Answer 250 Kanji correctly",
    "Learn 250 new Vocabulary words": "Learn 250 new Vocabulary words",
    "Achieve a 100% perfect score in five sessions": "Achieve a 100% perfect score in five sessions",
    "Answer 300 questions correctly in total": "Answer 300 questions correctly in total",

    // Dictionary
    "Search through over 9,000 Kanji, Vocabulary, and Grammar points.": "Search through over 9,000 Kanji, Vocabulary, and Grammar points.",
    "Search Japanese or English...": "Search Japanese or English...",
    "All": "All",
    "kanji": "kanji",
    "vocabulary": "vocabulary",
    "grammar": "grammar",
    "reading": "reading",
    "orthography": "orthography",
    "paraphrase": "paraphrase",
    "usage": "usage",
    "fill_in_the_blank": "fill_in_the_blank",
    "scramble": "scramble",
    "No results found matching your search.": "No results found matching your search.",
    "Load More": "Load More",
    "meanings": "meanings",
    "context": "context",
    "options": "options",
    "answer": "answer",
    "example_sentence": "example_sentence",

    // Leaderboard
    "Global Leaderboard": "Global Leaderboard",
    "Top 50 learners ranked by XP. (Public profiles only)": "Top 50 learners ranked by XP. (Public profiles only)",
    "No public profiles found.": "No public profiles found.",
    "You": "You",
    "Anonymous": "Anonymous",
    "Your Current Rank": "Your Current Rank",

    // Suggestions
    "Feature Requests": "Feature Requests",
    "Roadmap": "Roadmap",
    "Shipped": "Shipped",
    "Rejected": "Rejected",
    "Vote on Ideas": "Vote on Ideas",
    "Coming Soon": "Coming Soon",
    "Recently Released": "Recently Released",
    "Declined Ideas": "Declined Ideas",
    "Help shape the future of Otakufy.": "Help shape the future of Otakufy.",
    "Features we are actively working on.": "Features we are actively working on.",
    "Things we have already built.": "Things we have already built.",
    "Ideas that don't fit our current vision.": "Ideas that don't fit our current vision.",
    "Submit Idea": "Submit Idea",
    "Log in to submit": "Log in to submit",
    "Trending": "Trending",
    "Top Rated": "Top Rated",
    "Newest": "Newest",
    "Nothing to see here right now.": "Nothing to see here right now.",
    "New Suggestion": "New Suggestion",
    "Title": "Title",
    "Similar ideas exist! Consider upvoting them instead:": "Similar ideas exist! Consider upvoting them instead:",
    "points": "points",
    "Details": "Details",
    "Submit Anonymously": "Submit Anonymously",
    "Your username and avatar will be hidden.": "Your username and avatar will be hidden.",
    "Submit Suggestion": "Submit Suggestion",

    // Practice / Quiz
    "Level": "Level",
    "Quick Review": "Quick Review",
    "Start Practice": "Start Practice",
    "Spaced Repetition (SRS)": "Spaced Repetition (SRS)",
    "Hiragana": "Hiragana",
    "Katakana": "Katakana",
    "Beginner": "Beginner",
    "Intermediate": "Intermediate",
    "Advanced": "Advanced",
    "Select Level": "Select Level",
    "Select Category": "Select Category",
    "Configure Quiz": "Configure Quiz",
    "Session Summary": "Session Summary",
    "Review Flashcards": "Review Flashcards",
    "Show Answer": "Show Answer",
    "Next Card": "Next Card",
    "Again": "Again",
    "Hard": "Hard",
    "Good": "Good",
    "Easy": "Easy",
    "Fetching questions...": "Fetching questions...",
    "SRS Queue Cleared!": "SRS Queue Cleared!",
    "You have zero Spaced Repetition reviews due right now. Incredible discipline! The algorithm will schedule more items when they are ready for review.": "You have zero Spaced Repetition reviews due right now. Incredible discipline! The algorithm will schedule more items when they are ready for review.",
    "Study Another Level": "Study Another Level",
    "Sign In Required for SRS": "Sign In Required for SRS",
    "Spaced Repetition (SRS) tracks your personal memory intervals and retention history over time. Please sign in or create a free account to unlock this feature.": "Spaced Repetition (SRS) tracks your personal memory intervals and retention history over time. Please sign in or create a free account to unlock this feature.",
    "Sign In / Register": "Sign In / Register",
    "No Questions Available Yet": "No Questions Available Yet",
    "Select Different Level": "Select Different Level",
    "Connection Issue": "Connection Issue",
    "We encountered an issue connecting to the practice database. Please verify your connection and try again.": "We encountered an issue connecting to the practice database. Please verify your connection and try again.",
    "Return to Level Selection": "Return to Level Selection",
    "Select a proficiency level to begin": "Select a proficiency level to begin",
    "Spaced Rep": "Spaced Rep",
    "JLPT Level": "JLPT Level",
    "Mixed Deck": "Mixed Deck",
    "Global": "Global",
    "Question Format": "Question Format",
    "Example": "Example",
    "Solution": "Solution",
    "Overview": "Overview",
    "New Session": "New Session",
    "questions": "questions",
    "cards": "cards",
    "Start Study": "Start Study",
    "Saved Sessions": "Saved Sessions",
    "Progress": "Progress",
    "Resume": "Resume",
    "Mission Complete": "Mission Complete",
    "XP Earned": "XP Earned",
    "Accuracy": "Accuracy",
    "Mistakes": "Mistakes",
    "Items to review": "Items to review",
    "Session Finished": "Session Finished",
    "Return to Dashboard": "Return to Dashboard",
    "Review Mistakes": "Review Mistakes",
    "Correct Answer:": "Correct Answer:",
    "Added to SRS": "Added to SRS",
    "Add to SRS": "Add to SRS",
    "Milestone Unlocked": "Milestone Unlocked",
    "Level Up!": "Level Up!",
    "Continue Journey": "Continue Journey",
    "Achievement Unlocked": "Achievement Unlocked",
    "Awesome": "Awesome",
    "This comprehensive drill will dynamically cycle through all JLPT vocabulary formats. Carefully read the instruction header for each question during the quiz, as the format will constantly change.": "This comprehensive drill will dynamically cycle through all JLPT vocabulary formats. Carefully read the instruction header for each question during the quiz, as the format will constantly change.",
    "This deck currently holds": "This deck currently holds",
    "How many would you like to study?": "How many would you like to study?",
    "Slot": "Slot",
    "is empty": "is empty",
    "out of": "out of",
    "correct": "correct",
    "Syncing Profile...": "Syncing Profile...",
    "Progress Saved": "Progress Saved",
    "Authentication Required": "Authentication Required",
    "Please sign in to access your Friends and Social Hub.": "Please sign in to access your Friends and Social Hub.",
    "Connect with friends, accept friend requests, and discover fellow learners.": "Connect with friends, accept friend requests, and discover fellow learners.",
    "Requests": "Requests",
    "Add Friend": "Add Friend",
    "Search & filter friends by name or #ID...": "Search & filter friends by name or #ID...",
    "Search & filter requests by name or #ID...": "Search & filter requests by name or #ID...",
    "Enter exact tag e.g. Sakura#2640": "Enter exact tag e.g. Sakura#2640",
    "Clear": "Clear",
    "Filtering friends list.": "Filtering friends list.",
    "Filtering pending requests.": "Filtering pending requests.",
    "Exact match only — enter the full tag including #0000.": "Exact match only — enter the full tag including #0000.",
    "No friends added yet.": "No friends added yet.",
    "Find & Add Friends": "Find & Add Friends",
    "No one with that name could be found": "No one with that name could be found",
    "No pending friend requests.": "No pending friend requests.",
    "wants to be friends": "wants to be friends",
    "Accept": "Accept",
    "Decline": "Decline",
    "Outgoing": "Outgoing",
    "Enter an exact tag above to find someone, e.g. Sakura#2640": "Enter an exact tag above to find someone, e.g. Sakura#2640",
    "Pending": "Pending",
    "No outgoing friend requests.": "No outgoing friend requests.",
    "Request sent · awaiting response": "Request sent · awaiting response",
    "Withdraw": "Withdraw",
    "How does the Spaced Repetition (SRS) work?": "How does the Spaced Repetition (SRS) work?",
    "Otakufy uses an advanced Spaced Repetition System. When you answer a question correctly, the time before you see it again increases (from hours to days, to weeks). If you miss it, the interval resets, ensuring you see the things you struggle with more frequently until they enter your long-term memory.": "Otakufy uses an advanced Spaced Repetition System. When you answer a question correctly, the time before you see it again increases (from hours to days, to weeks). If you miss it, the interval resets, ensuring you see the things you struggle with more frequently until they enter your long-term memory.",
    "When do Daily Quests reset?": "When do Daily Quests reset?",
    "Daily Quests reset exactly at Midnight (00:00) in your local timezone. Make sure to complete your quests and claim your rewards before the clock strikes twelve!": "Daily Quests reset exactly at Midnight (00:00) in your local timezone. Make sure to complete your quests and claim your rewards before the clock strikes twelve!",
    "How is XP calculated?": "How is XP calculated?",
    "XP is earned by answering quiz questions correctly and completing Daily Quests. Harder questions (like N1 Kanji) reward more XP than easier ones. Your total XP dictates your rank on the Global Leaderboard.": "XP is earned by answering quiz questions correctly and completing Daily Quests. Harder questions (like N1 Kanji) reward more XP than easier ones. Your total XP dictates your rank on the Global Leaderboard.",
    "Why isn't my Japanese keyboard input working?": "Why isn't my Japanese keyboard input working?",
    "If you are having trouble typing in Hiragana/Katakana, ensure your OS-level IME (Input Method Editor) is switched to Japanese mode. For most Windows users, pressing 'Alt + ~' toggles this. For Mac, use 'Control + Shift + J'.": "If you are having trouble typing in Hiragana/Katakana, ensure your OS-level IME (Input Method Editor) is switched to Japanese mode. For most Windows users, pressing 'Alt + ~' toggles this. For Mac, use 'Control + Shift + J'.",
    "Help & Support": "Help & Support",
    "Need a hand with your Japanese journey? Check out the guides below or reach out to the community for assistance.": "Need a hand with your Japanese journey? Check out the guides below or reach out to the community for assistance.",
    "Modes Explained": "Modes Explained",
    "Vocab & Kanji:": "Vocab & Kanji:",
    "Flashcard style memorization.": "Flashcard style memorization.",
    "Grammar:": "Grammar:",
    "Understand structural rules with sentence examples.": "Understand structural rules with sentence examples.",
    "Reading:": "Reading:",
    "Comprehension tests built for JLPT paragraphs.": "Comprehension tests built for JLPT paragraphs.",
    "The Dictionary": "The Dictionary",
    "Use the Dictionary tab to search for specific words. It breaks down the Kanji, displays Furigana, and provides JLPT context instantly.": "Use the Dictionary tab to search for specific words. It breaks down the Kanji, displays Furigana, and provides JLPT context instantly.",
    "Join our Discord": "Join our Discord",
    "Chat with learners & report bugs": "Chat with learners & report bugs",
    "Direct Support": "Direct Support",
    "For critical account or billing issues:": "For critical account or billing issues:",
    "Don't send feature requests to support. Post them on our public board so the community can vote.": "Don't send feature requests to support. Post them on our public board so the community can vote.",
    "Go to Suggestions Board": "Go to Suggestions Board",
    "Feature Requests": "Feature Requests",
    "Roadmap": "Roadmap",
    "Shipped": "Shipped",
    "Rejected": "Rejected",
    "Trending": "Trending",
    "Top Rated": "Top Rated",
    "Newest": "Newest",
    "Nothing to see here right now.": "Nothing to see here right now.",
    "Vote on Ideas": "Vote on Ideas",
    "Coming Soon": "Coming Soon",
    "Recently Released": "Recently Released",
    "Declined Ideas": "Declined Ideas",
    "Help shape the future of Otakufy.": "Help shape the future of Otakufy.",
    "Features we are actively working on.": "Features we are actively working on.",
    "Things we have already built.": "Things we have already built.",
    "Ideas that don't fit our current vision.": "Ideas that don't fit our current vision.",
    "Submit Idea": "Submit Idea",
    "Log in to submit": "Log in to submit",
    "New": "New",
    "Under Review": "Under Review",
    "Planned": "Planned",
    "Admin:": "Admin:",
    "Anonymous": "Anonymous",
    "Gateway": "Gateway",
    "Identify Yourself": "Identify Yourself",
    "Email Address": "Email Address",
    "Password": "Password",
    "Forgot Password?": "Forgot Password?",
    "Generating Verification Mail...": "Generating Verification Mail...",
    "Please hold on for just a second! We are communicating with Brevo's secure SMTP servers right now to generate and dispatch your confirmation link.": "Please hold on for just a second! We are communicating with Brevo's secure SMTP servers right now to generate and dispatch your confirmation link.",
    "Verifying account credentials & logging in...": "Verifying account credentials & logging in...",
    "Email Dispatched Successfully!": "Email Dispatched Successfully!",
    "Login": "Login",
    "Register": "Register",
    "Or": "Or",
    "Continue with Google": "Continue with Google",
    "Enter your account email below. We will send a secure recovery link so you can reset your password immediately.": "Enter your account email below. We will send a secure recovery link so you can reset your password immediately.",
    "Account Email": "Account Email",
    "Send Recovery Link": "Send Recovery Link",
    "Back": "Back",
    "Password Requirements": "Password Requirements",
    "At least 8 characters": "At least 8 characters",
    "Contains a lowercase letter (a-z)": "Contains a lowercase letter (a-z)",
    "Contains an uppercase letter (A-Z)": "Contains an uppercase letter (A-Z)",
    "Contains a number (0-9)": "Contains a number (0-9)",
    "Contains a symbol (!@#$%^&*...)": "Contains a symbol (!@#$%^&*...)",
    "Suggestions": "Suggestions",
    "Active": "Active",
    "Dojo Interrupted": "Dojo Interrupted",
    "Study Glitch": "Study Glitch",
    "An unexpected disturbance disrupted your study session. Don't worry — your Satori points and streak data are safe.": "An unexpected disturbance disrupted your study session. Don't worry — your Satori points and streak data are safe.",
    "Error Details:": "Error Details:",
    "Try Again": "Try Again",
    "Satori Lost": "Satori Lost",
    "Wandering in the Fog": "Wandering in the Fog",
    "You have drifted into the uncharted void between study decks. This realm does not exist or has not yet been unlocked on your Japanese learning journey.": "You have drifted into the uncharted void between study decks. This realm does not exist or has not yet been unlocked on your Japanese learning journey.",
    "Return to Dashboard": "Return to Dashboard",
    "Study Kanji": "Study Kanji",

    // Settings
    "Application Theme": "Application Theme",
    "Toggle between dark and light mode universally.": "Toggle between dark and light mode universally.",
    "Application Language": "Application Language",
    "Toggle between English and literal Japanese across the entire site.": "Toggle between English and literal Japanese across the entire site.",
    "Show Furigana (振り仮名)": "Show Furigana (振り仮名)",
    "Display reading aids above kanji characters during practice.": "Display reading aids above kanji characters during practice.",
    "Audio Pronunciation": "Audio Pronunciation",
    "Automatically play native Japanese audio on flashcard flip.": "Automatically play native Japanese audio on flashcard flip.",
    "Daily XP Goal": "Daily XP Goal",
    "Set your target XP points to achieve every single day.": "Set your target XP points to achieve every single day.",
    "SRS Retention Rate": "SRS Retention Rate",
    "Target long-term retention interval speed for review flashcards.": "Target long-term retention interval speed for review flashcards.",

    // Profile & Settings
    "Profile Settings": "Profile Settings",
    "Username": "Username",
    "Email Address": "Email Address",
    "Current Password": "Current Password",
    "New Email": "New Email",
    "Change Email": "Change Email",
    "Privacy & Visibility": "Privacy & Visibility",
    "Public (Show everywhere)": "Public (Show everywhere)",
    "Friends Only": "Friends Only",
    "Private (Hide from leaderboard)": "Private (Hide from leaderboard)",
    "Control who can view your XP, streak, and progression milestones.": "Control who can view your XP, streak, and progression milestones.",
    "Confirm New Email": "Confirm New Email",
    "Continue with Google (Instant Verification)": "Continue with Google (Instant Verification)",
    "Customize your Otakufy experience.": "Customize your Otakufy experience.",
    "Set a personal daily target for your own motivation. (Your streak extends automatically just by playing!)": "Set a personal daily target for your own motivation. (Your streak extends automatically just by playing!)",
    "Global Preferences": "Global Preferences",
    "Show Romaji (ローマ字)": "Show Romaji (ローマ字)",
    "Display english alphabet readings alongside Japanese text.": "Display english alphabet readings alongside Japanese text.",
    "Auto-Play Audio": "Auto-Play Audio",
    "Daily XP": "Daily XP",
    "Automatically read sentences aloud when revealing answers.": "Automatically read sentences aloud when revealing answers.",
    "Identity & Settings": "Identity & Settings",
    "Manage your public identity, account credentials, and visibility preferences.": "Manage your public identity, account credentials, and visibility preferences.",
    "Public Profile & Avatar": "Public Profile & Avatar",
    "Update your photo and display name across leaderboards and social hub.": "Update your photo and display name across leaderboards and social hub.",
    "Change": "Change",
    "Remove Photo": "Remove Photo",
    "Display Name": "Display Name",
    "Update": "Update",
    "Account Status:": "Account Status:",
    "Active Member": "Active Member",
    "Current Progression": "Current Progression",
    "Your active XP milestones and level target.": "Your active XP milestones and level target.",
    "Completed": "Completed",
    "to Level": "to Level",
    "Account Email": "Account Email",
    "Private": "Private",
    "The primary email associated with your authentication.": "The primary email associated with your authentication.",
    "Reveal": "Reveal",
    "Hide": "Hide",
    "Secure Email Modification": "Secure Email Modification",
    "For account security, please verify your identity before changing your registered email address.": "For account security, please verify your identity before changing your registered email address.",
    "New Email Address": "New Email Address",
    "Forgot Password?": "Forgot Password?",
    "Or Instant Google Link": "Or Instant Google Link",
    "Public (Recommended)": "Public (Recommended)",
    "Fully visible on the global leaderboard and public profile searches.": "Fully visible on the global leaderboard and public profile searches.",
    "Hidden from leaderboards. Only added friends can see your stats.": "Hidden from leaderboards. Only added friends can see your stats.",
    "Your stats and progression are completely hidden from everyone.": "Your stats and progression are completely hidden from everyone.",
    "Accessibility & Performance": "Accessibility & Performance",
    "Disable UI Animations": "Disable UI Animations",
    "Turn off all interface animations and transitions.": "Turn off all interface animations and transitions.",
    "Disable Particle Animations": "Disable Particle Animations",
    "Turn off seasonal background effects like falling cherry blossoms.": "Turn off seasonal background effects like falling cherry blossoms."
  },
  ja: {
    // Navigation & General
    "Dashboard": "ダッシュボード",
    "Dictionary": "辞書",
    "Leaderboard": "リーダーボード",
    "Suggestions": "ご提案・ご意見",
    "Practice": "練習",
    "Social Hub": "ソーシャルハブ",
    "Settings": "設定",
    "Profile": "プロフィール",
    "Friends": "フレンド",
    "Help & Support": "ヘルプ＆サポート",
    "Logout": "ログアウト",
    "Sign Out": "ログアウト",
    "Sign In": "ログイン",
    "Login": "ログイン",
    "Register": "新規登録",
    "Search": "検索",
    "Loading...": "読み込み中...",
    "Save": "保存",
    "Cancel": "キャンセル",
    "Back": "戻る",
    "Help": "ヘルプ",
    "Active": "選択中",
    "Otakufy Member": "Otakufyメンバー",
    
    // Dashboard & Objectives
    "Welcome back.": "お帰りなさいませ",
    "\"Continue your path to fluency.\"": "「流暢な日本語習得への旅を続けましょう。」",
    "Day Streak": "日連続記録",
    "Total XP": "総経験値",
    "LEVEL": "レベル",
    "study_modules": "学習モジュール",
    "Kanji": "漢字",
    "Vocabulary": "単語",
    "Grammar": "文法",
    "Reading": "読解",
    "Listening": "聴解",
    "Random": "ランダム",
    "smart_review": "スマート復習",
    "Spaced Repetition": "間隔反復学習 (SRS)",
    "Power through your due SRS reviews. The algorithm determines exactly what you need to study for optimal long-term retention. If your queue is empty, you'll automatically start a random": "予定されているSRS復習カードを学習しましょう。アルゴリズムが長期記憶に最適な学習内容を自動判定します。キューが空の場合は、自動的に",
    "deck.": "のランダムデッキを開始します。",
    "Start SRS Review": "SRS復習を開始",
    "daily_objectives": "今日の目標",
    "No quests assigned today.": "本日のクエストはありません。",
    "Claim": "報酬受取",
    "Answer 10 Kanji correctly": "漢字を10問正解する",
    "Learn 10 new Vocabulary words": "新しい単語を10個学習する",
    "Complete 5 Grammar questions": "文法問題を5問完了する",
    "Complete 5 Listening exercises": "聴解問題を5問完了する",
    "Complete 1 quiz session today": "今日中にクイズセッションを1回完了する",
    "Get 3 correct answers in a row": "3問連続で正解する",
    "Answer 20 questions correctly in total": "合計20問正解する",
    "Answer 20 Kanji correctly": "漢字を20問正解する",
    "Learn 20 new Vocabulary words": "新しい単語を20個学習する",
    "Complete 10 Grammar questions": "文法問題を10問完了する",
    "Complete 10 Listening exercises": "聴解問題を10問完了する",
    "Complete 2 quiz sessions today": "今日中にクイズセッションを2回完了する",
    "Get 5 correct answers in a row": "5問連続で正解する",
    "Answer 30 questions correctly in total": "合計30問正解する",
    "Answer 30 Kanji correctly": "漢字を30問正解する",
    "Learn 30 new Vocabulary words": "新しい単語を30個学習する",
    "Complete 15 Grammar questions": "文法問題を15問完了する",
    "Complete 15 Listening exercises": "聴解問題を15問完了する",
    "Complete 3 quiz sessions today": "今日中にクイズセッションを3回完了する",
    "Get 10 correct answers in a row": "10問連続で正解する",
    "Answer 50 Kanji correctly": "漢字を50問正解する",
    "Learn 50 new Vocabulary words": "新しい単語を50個学習する",
    "Complete 30 Grammar questions": "文法問題を30問完了する",
    "Complete 30 Listening exercises": "聴解問題を30問完了する",
    "Complete 5 quiz sessions today": "今日中にクイズセッションを5回完了する",
    "Get 15 correct answers in a row": "15問連続で正解する",
    "Answer 60 questions correctly in total": "合計60問正解する",
    "Answer 70 Kanji correctly": "漢字を70問正解する",
    "Learn 70 new Vocabulary words": "新しい単語を70個学習する",
    "Complete 40 Grammar questions": "文法問題を40問完了する",
    "Complete 40 Listening exercises": "聴解問題を40問完了する",
    "Complete 7 quiz sessions today": "今日中にクイズセッションを7回完了する",
    "Achieve a 100% perfect score in one session": "1回のセッションで100%満点を達成する",
    "Get 25 correct answers in a row": "25問連続で正解する",
    "Answer 80 questions correctly in total": "合計80問正解する",
    "Answer 90 Kanji correctly": "漢字を90問正解する",
    "Learn 90 new Vocabulary words": "新しい単語を90個学習する",
    "Complete 50 Grammar questions": "文法問題を50問完了する",
    "Complete 50 Listening exercises": "聴解問題を50問完了する",
    "Complete 10 quiz sessions today": "今日中にクイズセッションを10回完了する",
    "Answer 120 Kanji correctly": "漢字を120問正解する",
    "Learn 120 new Vocabulary words": "新しい単語を120個学習する",
    "Complete 80 Grammar questions": "文法問題を80問完了する",
    "Complete 80 Listening exercises": "聴解問題を80問完了する",
    "Complete 15 quiz sessions today": "今日中にクイズセッションを15回完了する",
    "Achieve a 100% perfect score in two sessions": "2回のセッションで100%満点を達成する",
    "Get 50 correct answers in a row": "50問連続で正解する",
    "Answer 150 questions correctly in total": "合計150問正解する",
    "Answer 150 Kanji correctly": "漢字を150問正解する",
    "Learn 150 new Vocabulary words": "新しい単語を150個学習する",
    "Complete 100 Grammar questions": "文法問題を100問完了する",
    "Complete 100 Listening exercises": "聴解問題を100問完了する",
    "Complete 20 quiz sessions today": "今日中にクイズセッションを20回完了する",
    "Achieve a 100% perfect score in three sessions": "3回のセッションで100%満点を達成する",
    "Get 80 correct answers in a row": "80問連続で正解する",
    "Answer 200 questions correctly in total": "合計200問正解する",
    "Answer 250 Kanji correctly": "漢字を250問正解する",
    "Learn 250 new Vocabulary words": "新しい単語を250個学習する",
    "Achieve a 100% perfect score in five sessions": "5回のセッションで100%満点を達成する",
    "Answer 300 questions correctly in total": "合計300問正解する",

    // Dictionary
    "Search through over 9,000 Kanji, Vocabulary, and Grammar points.": "9,000以上の漢字、単語、文法事項を検索できます。",
    "Search Japanese or English...": "日本語または英語で検索...",
    "All": "すべて",
    "kanji": "漢字",
    "vocabulary": "単語",
    "grammar": "文法",
    "reading": "読み",
    "orthography": "表記",
    "paraphrase": "言い換え",
    "usage": "用法",
    "fill_in_the_blank": "穴埋め",
    "scramble": "並べ替え",
    "No results found matching your search.": "検索条件に一致する結果は見つかりませんでした。",
    "Load More": "もっと見る",
    "meanings": "意味",
    "context": "文脈",
    "options": "選択肢",
    "answer": "正解",
    "example_sentence": "例文",

    // Leaderboard
    "Global Leaderboard": "世界ランキング",
    "Top 50 learners ranked by XP. (Public profiles only)": "経験値上位50名の学習者 (公開プロフィールのみ)",
    "No public profiles found.": "公開プロフィールは見つかりませんでした。",
    "You": "あなた",
    "Anonymous": "匿名ユーザー",
    "Your Current Rank": "あなたの現在の順位",

    // Suggestions
    "Feature Requests": "機能リクエスト",
    "Roadmap": "ロードマップ",
    "Shipped": "リリース済み",
    "Rejected": "見送り",
    "Vote on Ideas": "アイデアに投票",
    "Coming Soon": "近日公開",
    "Recently Released": "最近のリリース",
    "Declined Ideas": "見送りとなったアイデア",
    "Help shape the future of Otakufy.": "Otakufyの未来を一緒に作りましょう。",
    "Features we are actively working on.": "現在開発中の機能です。",
    "Things we have already built.": "既に実装済みの機能です。",
    "Ideas that don't fit our current vision.": "現在のビジョンには適合しなかったアイデアです。",
    "Submit Idea": "アイデアを投稿",
    "Log in to submit": "ログインして投稿",
    "Trending": "トレンド",
    "Top Rated": "高評価",
    "Newest": "新着",
    "Nothing to see here right now.": "現在ここに表示するアイテムはありません。",
    "New Suggestion": "新規アイデア投稿",
    "Title": "タイトル",
    "Similar ideas exist! Consider upvoting them instead:": "似たアイデアが既に投稿されています！代わりに賛成投票をご検討ください：",
    "points": "ポイント",
    "Details": "詳細",
    "Submit Anonymously": "匿名で投稿",
    "Your username and avatar will be hidden.": "ユーザー名とアイコンが非公開になります。",
    "Submit Suggestion": "アイデアを送信",

    // Practice / Quiz
    "Level": "レベル",
    "Quick Review": "クイック復習",
    "Start Practice": "学習を開始",
    "Spaced Repetition (SRS)": "間隔反復学習 (SRS)",
    "Hiragana": "ひらがな",
    "Katakana": "カタカナ",
    "Beginner": "初級",
    "Intermediate": "中級",
    "Advanced": "上級",
    "Select Level": "レベルを選択",
    "Select Category": "カテゴリーを選択",
    "Configure Quiz": "クイズ設定",
    "Session Summary": "セッション概要",
    "Review Flashcards": "フラッシュカード復習",
    "Show Answer": "答えを表示",
    "Next Card": "次のカード",
    "Again": "もう一度",
    "Hard": "難しい",
    "Good": "普通",
    "Easy": "簡単",
    "Fetching questions...": "問題を読み込み中...",
    "SRS Queue Cleared!": "SRSの復習キューが空になりました！",
    "You have zero Spaced Repetition reviews due right now. Incredible discipline! The algorithm will schedule more items when they are ready for review.": "現在学習予定のSRS復習カードはありません。素晴らしい継続力です！次の復習時期が来たら自動的にスケジュールされます。",
    "Study Another Level": "別のレベルを学習",
    "Sign In Required for SRS": "SRS機能にはログインが必要です",
    "Spaced Repetition (SRS) tracks your personal memory intervals and retention history over time. Please sign in or create a free account to unlock this feature.": "間隔反復学習 (SRS) はあなたの長期記憶や復習スケジュールを記録します。この機能を利用するには、ログインまたは無料会員登録を行ってください。",
    "Sign In / Register": "ログイン / 新規登録",
    "No Questions Available Yet": "問題がまだありません",
    "Select Different Level": "別のレベルを選択",
    "Connection Issue": "接続エラー",
    "We encountered an issue connecting to the practice database. Please verify your connection and try again.": "データベース接続時にエラーが発生しました。インターネット接続を確認し、もう一度お試しください。",
    "Return to Level Selection": "レベル選択に戻る",
    "Select a proficiency level to begin": "難易度レベルを選択してください",
    "Spaced Rep": "間隔反復 (SRS)",
    "JLPT Level": "JLPTレベル",
    "Mixed Deck": "総合問題",
    "Global": "全範囲",
    "Question Format": "出題形式",
    "Example": "例",
    "Solution": "解説",
    "Overview": "概要",
    "New Session": "新規学習セッション",
    "questions": "問題",
    "cards": "カード",
    "Start Study": "学習を開始",
    "Saved Sessions": "保存されたセッション",
    "Progress": "進行状況",
    "Resume": "再開",
    "Mission Complete": "ミッション達成",
    "XP Earned": "獲得経験値",
    "Accuracy": "正答率",
    "Mistakes": "間違えた問題",
    "Items to review": "要復習アイテム",
    "Session Finished": "セッション終了",
    "Return to Dashboard": "ダッシュボードに戻る",
    "Review Mistakes": "間違えた問題の復習",
    "Correct Answer:": "正解:",
    "Added to SRS": "SRSに登録済み",
    "Add to SRS": "SRSに登録",
    "Milestone Unlocked": "マイルストーン達成",
    "Level Up!": "レベルアップ！",
    "Continue Journey": "学習を続ける",
    "Achievement Unlocked": "実績解除",
    "Awesome": "素晴らしい！",
    "This comprehensive drill will dynamically cycle through all JLPT vocabulary formats. Carefully read the instruction header for each question during the quiz, as the format will constantly change.": "この総合ドリルでは、すべてのJLPT単語出題形式がダイナミックに循環します。クイズ進行中は出題形式が常に変化するため、問題ごとの指示ヘッダーを注意深くお読みください。",
    "This deck currently holds": "このデッキに収録されている問題数は",
    "How many would you like to study?": "何問学習しますか？",
    "Slot": "スロット",
    "is empty": "は空です",
    "out of": "/ 最大",
    "correct": "問正解",
    "Syncing Profile...": "プロフィールを同期中...",
    "Progress Saved": "進行状況を保存しました",
    "Authentication Required": "認証が必要です",
    "Please sign in to access your Friends and Social Hub.": "フレンド機能やソーシャルハブにアクセスするにはログインしてください。",
    "Connect with friends, accept friend requests, and discover fellow learners.": "フレンドと繋がり、リクエストを承認し、他の学習者と交流しましょう。",
    "Requests": "リクエスト",
    "Add Friend": "フレンド追加",
    "Search & filter friends by name or #ID...": "名前や#IDでフレンドを検索・絞り込み...",
    "Search & filter requests by name or #ID...": "名前や#IDでリクエストを検索・絞り込み...",
    "Enter exact tag e.g. Sakura#2640": "正確なタグを入力 (例: Sakura#2640)",
    "Clear": "クリア",
    "Filtering friends list.": "フレンドリストを絞り込んでいます。",
    "Filtering pending requests.": "承認待ちリクエストを絞り込んでいます。",
    "Exact match only — enter the full tag including #0000.": "完全一致のみ — #0000を含む完全なタグを入力してください。",
    "No friends added yet.": "まだフレンドが追加されていません。",
    "Find & Add Friends": "フレンドを探して追加",
    "No one with that name could be found": "該当する名前のユーザーは見つかりませんでした",
    "No pending friend requests.": "保留中のフレンドリクエストはありません。",
    "wants to be friends": "フレンド申請が届いています",
    "Accept": "承認",
    "Decline": "拒否",
    "Outgoing": "送信済み",
    "Enter an exact tag above to find someone, e.g. Sakura#2640": "上記に完全なタグを入力してユーザーを検索 (例: Sakura#2640)",
    "Pending": "承認待ち",
    "No outgoing friend requests.": "送信済みのフレンドリクエストはありません。",
    "Request sent · awaiting response": "リクエスト送信済み · 相手の承認待ち",
    "Withdraw": "取り消し",
    "How does the Spaced Repetition (SRS) work?": "間隔反復学習 (SRS) はどのように機能しますか？",
    "Otakufy uses an advanced Spaced Repetition System. When you answer a question correctly, the time before you see it again increases (from hours to days, to weeks). If you miss it, the interval resets, ensuring you see the things you struggle with more frequently until they enter your long-term memory.": "Otakufyは高度な間隔反復学習システムを採用しています。問題に正解すると、次に表示されるまでの間隔が（時間単位から日数、週単位へと）長くなります。不正解の場合は間隔がリセットされ、苦手な問題を長期記憶に定着するまでより高頻度で復習することができます。",
    "When do Daily Quests reset?": "デイリークエストはいつリセットされますか？",
    "Daily Quests reset exactly at Midnight (00:00) in your local timezone. Make sure to complete your quests and claim your rewards before the clock strikes twelve!": "デイリークエストはお住まいのタイムゾーンの深夜零時（00:00）に正確にリセットされます。日付が変わる前にクエストを完了し、報酬を受け取ってください！",
    "How is XP calculated?": "XPはどのように計算されますか？",
    "XP is earned by answering quiz questions correctly and completing Daily Quests. Harder questions (like N1 Kanji) reward more XP than easier ones. Your total XP dictates your rank on the Global Leaderboard.": "XPはクイズの問題に正解したりデイリークエストを完了することで獲得できます。難易度の高い問題（N1の漢字など）ほど、より多くのXPが与えられます。獲得した合計XPによってグローバルリーダーボードの順位が決まります。",
    "Why isn't my Japanese keyboard input working?": "日本語のキーボード入力がうまく機能しないのはなぜですか？",
    "If you are having trouble typing in Hiragana/Katakana, ensure your OS-level IME (Input Method Editor) is switched to Japanese mode. For most Windows users, pressing 'Alt + ~' toggles this. For Mac, use 'Control + Shift + J'.": "ひらがな・カタカナの入力に問題がある場合は、OSのIME（日本語入力システム）が日本語モードに切り替わっていることを確認してください。Windowsユーザーは「Alt + ~」、Macユーザーは「Control + Shift + J」で切り替えが可能です。",
    "Help & Support": "ヘルプ＆サポート",
    "Need a hand with your Japanese journey? Check out the guides below or reach out to the community for assistance.": "日本語学習でお困りですか？以下のガイドをご確認いただくか、コミュニティにお問い合わせください。",
    "Modes Explained": "各モードの解説",
    "Vocab & Kanji:": "単語と漢字:",
    "Flashcard style memorization.": "フラッシュカード形式での記憶学習。",
    "Grammar:": "文法:",
    "Understand structural rules with sentence examples.": "例文を通じて構文ルールを深く理解。",
    "Reading:": "読解:",
    "Comprehension tests built for JLPT paragraphs.": "JLPT形式の長文読解テスト。",
    "The Dictionary": "辞書機能",
    "Use the Dictionary tab to search for specific words. It breaks down the Kanji, displays Furigana, and provides JLPT context instantly.": "辞書タブを使用して特定の単語を検索できます。漢字の構成やふりがな、JLPTの文脈情報を瞬時に確認できます。",
    "Join our Discord": "Discordサーバーに参加",
    "Chat with learners & report bugs": "他の学習者と交流したりバグを報告する",
    "Direct Support": "直接サポート",
    "For critical account or billing issues:": "重要なアカウントや決済に関する問題:",
    "Don't send feature requests to support. Post them on our public board so the community can vote.": "機能要望はサポートではなく、公開ボードに投稿してコミュニティの投票を募りましょう。",
    "Go to Suggestions Board": "ご意見・ご要望ボードへ移動",
    "Feature Requests": "機能リクエスト",
    "Roadmap": "ロードマップ",
    "Shipped": "リリース済み",
    "Rejected": "却下済み",
    "Trending": "トレンド",
    "Top Rated": "高評価",
    "Newest": "新着順",
    "Nothing to see here right now.": "現在表示する項目はありません。",
    "Vote on Ideas": "アイデアに投票する",
    "Coming Soon": "間もなく登場",
    "Recently Released": "最近リリースされた機能",
    "Declined Ideas": "見送りとなったアイデア",
    "Help shape the future of Otakufy.": "Otakufyの未来を一緒に作りましょう。",
    "Features we are actively working on.": "現在開発中の機能一覧です。",
    "Things we have already built.": "既に実装・公開済みの機能です。",
    "Ideas that don't fit our current vision.": "現在の方針には適合しないアイデアです。",
    "Submit Idea": "アイデアを投稿",
    "Log in to submit": "ログインして投稿",
    "New": "新規",
    "Under Review": "検討中",
    "Planned": "計画中",
    "Admin:": "管理者:",
    "Anonymous": "匿名ユーザー",
    "Gateway": "ゲートウェイ",
    "Identify Yourself": "本人確認",
    "Email Address": "メールアドレス",
    "Password": "パスワード",
    "Forgot Password?": "パスワードをお忘れですか？",
    "Generating Verification Mail...": "認証メールを作成中...",
    "Please hold on for just a second! We are communicating with Brevo's secure SMTP servers right now to generate and dispatch your confirmation link.": "しばらくお待ちください！現在、BrevoのセキュアなSMTPサーバーと通信し、確認リンクを作成・送信しています。",
    "Verifying account credentials & logging in...": "アカウント情報を照合し、ログインしています...",
    "Email Dispatched Successfully!": "メールの送信が完了しました！",
    "Login": "ログイン",
    "Register": "新規登録",
    "Or": "または",
    "Continue with Google": "Googleで続行",
    "Enter your account email below. We will send a secure recovery link so you can reset your password immediately.": "以下にアカウントのメールアドレスを入力してください。パスワードを再設定するためのセキュアなリカバリーリンクを送信します。",
    "Account Email": "アカウントメール",
    "Send Recovery Link": "リカバリーリンクを送信",
    "Back": "戻る",
    "Password Requirements": "パスワード要件",
    "At least 8 characters": "8文字以上",
    "Contains a lowercase letter (a-z)": "小文字(a-z)を含む",
    "Contains an uppercase letter (A-Z)": "大文字(A-Z)を含む",
    "Contains a number (0-9)": "数字(0-9)を含む",
    "Contains a symbol (!@#$%^&*...)": "記号(!@#$%^&*...)を含む",
    "Suggestions": "ご意見・ご要望",
    "Active": "表示中",
    "Dojo Interrupted": "道場の学習が中断されました",
    "Study Glitch": "学習グリッチ (不具合)",
    "An unexpected disturbance disrupted your study session. Don't worry — your Satori points and streak data are safe.": "予期せぬ障害により学習セッションが中断されました。悟りポイントやストリークデータは安全に保存されていますのでご安心ください。",
    "Error Details:": "エラー詳細:",
    "Try Again": "再試行",
    "Satori Lost": "悟りを喪失",
    "Wandering in the Fog": "霧の中を彷徨中",
    "You have drifted into the uncharted void between study decks. This realm does not exist or has not yet been unlocked on your Japanese learning journey.": "学習デッキ間の未知なる領域へ迷い込みました。このページは存在しないか、まだあなたの日本語学習の旅でアンロックされていません。",
    "Return to Dashboard": "ダッシュボードへ戻る",
    "Study Kanji": "漢字を学習する",

    // Settings
    "Application Theme": "アプリのテーマ",
    "Toggle between dark and light mode universally.": "ダークモードとライトモードを切り替えます。",
    "Application Language": "言語設定 (Language)",
    "Toggle between English and literal Japanese across the entire site.": "サイト全体の表記を英語と日本語で完全に切り替えます。",
    "Show Furigana (振り仮名)": "ふりがなを表示",
    "Display reading aids above kanji characters during practice.": "練習中に漢字の上部に読み仮名を表示します。",
    "Audio Pronunciation": "音声発音",
    "Automatically play native Japanese audio on flashcard flip.": "フラッシュカードをめくった際に日本語音声を自動再生します。",
    "Daily XP Goal": "目標経験値 (日次)",
    "Set your target XP points to achieve every single day.": "1日あたりの目標経験値を設定します。",
    "SRS Retention Rate": "SRS記憶保持率目標",
    "Target long-term retention interval speed for review flashcards.": "復習フラッシュカードの長期記憶保持インターバルを設定します。",

    // Profile & Settings
    "Profile Settings": "プロフィール設定",
    "Username": "ユーザー名",
    "Email Address": "メールアドレス",
    "Current Password": "現在のパスワード",
    "New Email": "新しいメールアドレス",
    "Change Email": "メールアドレス変更",
    "Privacy & Visibility": "公開設定",
    "Public (Show everywhere)": "全体に公開",
    "Friends Only": "フレンドのみ公開",
    "Private (Hide from leaderboard)": "非公開 (ランキングから除外)",
    "Control who can view your XP, streak, and progression milestones.": "経験値、連続学習記録、マイルストーンを誰が閲覧できるか設定します。",
    "Confirm New Email": "新しいメールを確認",
    "Continue with Google (Instant Verification)": "Googleで即時認証して続行",
    "Customize your Otakufy experience.": "Otakufyの各種設定をカスタマイズします。",
    "Set a personal daily target for your own motivation. (Your streak extends automatically just by playing!)": "モチベーション維持のための個人的な1日の目標を設定します。（連続記録はプレイするだけで自動的に延長されます！）",
    "Global Preferences": "共通設定",
    "Show Romaji (ローマ字)": "ローマ字を表示",
    "Display english alphabet readings alongside Japanese text.": "日本語と併せてアルファベット表記の読み仮名を表示します。",
    "Auto-Play Audio": "音声を自動再生",
    "Daily XP": "今日のXP",
    "Automatically read sentences aloud when revealing answers.": "解答を表示した際に例文や単語の音声を自動再生します。",
    "Identity & Settings": "認証・アカウント設定",
    "Manage your public identity, account credentials, and visibility preferences.": "公開プロフィール、アカウント認証情報、および公開範囲設定を管理します。",
    "Public Profile & Avatar": "公開プロフィール＆アイコン",
    "Update your photo and display name across leaderboards and social hub.": "ランキングやソーシャルハブに表示される写真や表示名を変更できます。",
    "Change": "変更",
    "Remove Photo": "削除",
    "Display Name": "表示名",
    "Update": "更新",
    "Account Status:": "アカウント状態:",
    "Active Member": "アクティブメンバー",
    "Current Progression": "現在の進行状況",
    "Your active XP milestones and level target.": "現在の経験値マイルストーンと次のレベルへの目標です。",
    "Completed": "達成",
    "to Level": "で次のレベル:",
    "Account Email": "アカウントメールアドレス",
    "Private": "非公開",
    "The primary email associated with your authentication.": "認証に関連付けられている主メールアドレスです。",
    "Reveal": "表示",
    "Hide": "非表示",
    "Secure Email Modification": "安全なメールアドレス変更",
    "For account security, please verify your identity before changing your registered email address.": "セキュリティのため、メールアドレスを変更する前に本人確認を行ってください。",
    "New Email Address": "新しいメールアドレス",
    "Forgot Password?": "パスワードをお忘れですか？",
    "Or Instant Google Link": "またはGoogleアカウントで即時連携",
    "Public (Recommended)": "全体に公開 (推奨)",
    "Fully visible on the global leaderboard and public profile searches.": "世界ランキングおよび公開プロフィール検索に完全に表示されます。",
    "Hidden from leaderboards. Only added friends can see your stats.": "ランキングからは除外されます。フレンドのみがステータスを閲覧できます。",
    "Your stats and progression are completely hidden from everyone.": "あなたのステータスや進行状況はすべてのユーザーから完全に隠されます。",
    "Accessibility & Performance": "アクセシビリティとパフォーマンス",
    "Disable UI Animations": "UIアニメーションを無効化",
    "Turn off all interface animations and transitions.": "すべてのインターフェースアニメーションとトランジションをオフにします。",
    "Disable Particle Animations": "パーティクルアニメーションを無効化",
    "Turn off seasonal background effects like falling cherry blossoms.": "舞い散る桜などの季節の背景エフェクトをオフにします。"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    if (typeof window !== "undefined") {
      try {
        const saved = localStorage.getItem("app_lang");
        if (saved === "ja" || saved === "en") return saved;
      } catch (e) {}
    }
    return "en";
  });

  useEffect(() => {
    document.documentElement.setAttribute("lang", lang);
  }, [lang]);

  const setLang = useCallback((newLang) => {
    setLangState(newLang);
    localStorage.setItem("app_lang", newLang);
    document.documentElement.setAttribute("lang", newLang);
  }, []);

  const toggleLang = useCallback(() => {
    const nextLang = lang === "en" ? "ja" : "en";
    setLang(nextLang);
  }, [lang, setLang]);

  const t = useCallback((key) => {
    if (!key) return "";
    return TRANSLATIONS[lang]?.[key] !== undefined ? TRANSLATIONS[lang][key] : (TRANSLATIONS.en[key] || key);
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
